services:
  app:
    build:
      context: ../../
      dockerfile: ./docker/development/Dockerfile
      target: builder
      args:
        BUILDPLATFORM: "linux/arm64"
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: