"""Create Post Table

Revision ID: fffffffff0001
Revises: 
Create Date: 2023-03-31 14:33:52.288399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fffffffff0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_request_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var5', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var10', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unique_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_impression_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var6', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requesting_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var9', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var2', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referer', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var3', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var7', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var8', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var1', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proxy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('var4', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_campaign_request_log_campaign_uuid'))
        batch_op.alter_column('campaign_uuid',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=256),
                              existing_nullable=True)
        batch_op.alter_column('id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.text('"identity"(653664, 0, \'0,1\'::text)'))

    with op.batch_alter_table('campaign_impression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent_string', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('impression_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requesting_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referer', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proxy_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_campaign_impression_advertiser_id'))
        batch_op.alter_column('campaign_uuid',
                              existing_type=sa.String(length=5000),
                              type_=sa.VARCHAR(length=256),
                              existing_nullable=True)
        batch_op.alter_column('advertiser_id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              existing_nullable=True)
        batch_op.alter_column('id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.text('"identity"(190997, 0, \'0,1\'::text)'))

    op.create_table('campaign_statistic',
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='campaign_statistic_pkey'),
                    redshift_distkey='campaign_id',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('partner_id',)
                    )
    op.create_table('campaign_request_log_bk',
                    sa.Column('campaign_impression_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var3', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('unique_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('requesting_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('var1', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('var10', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('proxy_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('var7', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var6', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('var5', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var8', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var2', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var9', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('language', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('var4', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__conversion_board_mv__0',
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('offer_name', sa.VARCHAR(length=1020), autoincrement=False, nullable=True),
                    sa.Column('partner_name', sa.VARCHAR(length=2041), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('advertiser_statistic',
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('advertiser_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.Column('epc_min', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('epc_max', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('cvr_min', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.Column('cvr_max', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='advertiser_statistic_pkey'),
                    redshift_distkey='advertiser_id',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('id',)
                    )
    op.create_table('landing_page_view_logs',
                    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('date', sa.DATE(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('landing_page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('page_alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='landing_page_view_logs_pkey'),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('click_log',
                    sa.Column('id', sa.BIGINT(), server_default=sa.text('"identity"(166826, 0, \'0,1\'::text)'), autoincrement=False, nullable=False),
                    sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('var3', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_impression_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var1', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var6', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('var8', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var7', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('unique_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var2', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('var9', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var5', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('var10', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('var4', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('requesting_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('redirect_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('proxy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='click_log_pkey'),
                    redshift_distkey='id',
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__device_statistic_mv__0',
                    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('traffic_count', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_traffic_count', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('postback_log',
                    sa.Column('id', sa.BIGINT(), server_default=sa.text('"identity"(166844, 0, \'0,1\'::text)'), autoincrement=False, nullable=False),
                    sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('sub4_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_relay', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_duplicate', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_proxy', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_multiple_events', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('payout', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sub1_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_manually_approve_conversion', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('sub3_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('landing_page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('flagged_reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_tor', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('fraud_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('macro_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('revenue_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_vpn', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('specific_tracking_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('external_conversion_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('payout_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('postback_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_hosting', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('flagged_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sale_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('revenue', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('bonus', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('campaign_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('event_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sale_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_timezone', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('sub2_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sub5_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referral_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('proxy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('status', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('postback_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('ts_postback_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='postback_log_pkey'),
                    redshift_distkey='id',
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__budget_check_extracted_yearly_mv__0',
                    sa.Column('grvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('grvar_2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('grvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_2', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('aggvar_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('num_rec', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle='EVEN',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__country_statistic_mv__0',
                    sa.Column('name', sa.VARCHAR(length=1020), autoincrement=False, nullable=True),
                    sa.Column('traffic_count', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_traffic_count', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__vertical_statistic_mv__0',
                    sa.Column('vertical_id', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
                    sa.Column('total_counts', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_conversion', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey='vertical_id',
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('offer_request_log',
                    sa.Column('id', sa.BIGINT(), server_default=sa.text('"identity"(166835, 0, \'0,1\'::text)'), autoincrement=False, nullable=False),
                    sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('macro_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_hosting', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('specific_tracking_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('flagged_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_proxy', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('fraud_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('landing_page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_vpn', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_tor', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_relay', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('flagged_reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_timezone', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('proxy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='offer_request_log_pkey'),
                    redshift_distkey='id',
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__budget_check_extracted_monthly_mv__0',
                    sa.Column('grvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('grvar_2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('grvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_2', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('aggvar_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('num_rec', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle='EVEN',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('offer_statistic',
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('advertiser_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_payout', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('epc', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('cvr', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.Column('score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.Column('score_last_30_days', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='offer_statistic_pkey'),
                    redshift_distkey='offer_id',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('id',)
                    )
    op.create_table('conversion',
                    sa.Column('id', sa.BIGINT(), server_default=sa.text('"identity"(165838, 0, \'0,1\'::text)'), autoincrement=False, nullable=False),
                    sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('sub4_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('connection_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('mobile_carrier', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('click_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_relay', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_duplicate', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_proxy', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('is_multiple_events', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('payout', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('sub1_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('device_os_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_manually_approve_conversion', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('browser', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('sub3_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('landing_page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('timezone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('flagged_reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_tor', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('device_model', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('fraud_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('macro_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('revenue_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_os', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_vpn', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('isp', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('specific_tracking_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('external_conversion_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('browser_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('postal', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('payout_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('postback_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('is_hosting', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('flagged_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('campaign_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('cost_model', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('device_brand', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sale_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('lander_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('revenue', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('region', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('bonus', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('user_agent_string', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('campaign_uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('event_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sale_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_timezone', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('sub2_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('sub5_adv', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('device_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referral_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('proxy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('postback_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('ts_postback_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='conversion_pkey'),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('id',)
                    )
    op.create_table('traffic_source_statistic',
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('traffic_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='traffic_source_statistic_pkey'),
                    redshift_distkey='traffic_source_id',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('partner_id', 'traffic_source_id')
                    )
    op.create_table('lander_statistic',
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), server_default=sa.text("('now'::text)::timestamp without time zone"), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('lander_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total_click', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='lander_statistic_pkey'),
                    redshift_distkey='lander_id',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=('partner_id',)
                    )
    op.create_table('action_log',
                    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('created_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('landing_page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('client_id', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('user_agent', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
                    sa.Column('cookies_string', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('referer', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_redshift.dialect.TIMESTAMPTZ(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('campaign_offer_request_log',
                    sa.Column('uuid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__advertiser_last30day_statistic_mv__0',
                    sa.Column('advertiser_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_application', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_application_approve', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    redshift_distkey='advertiser_id',
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__budget_check_extracted_weekly_mv__0',
                    sa.Column('grvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('grvar_2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('grvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_2', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('aggvar_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('num_rec', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle='EVEN',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__budget_check_extracted_daily_mv__0',
                    sa.Column('grvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('grvar_2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('grvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_2', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('aggvar_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('num_rec', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle='EVEN',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__budget_check_extracted_lifetime_mv__0',
                    sa.Column('grvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_3', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_1', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('__mv_non_null_count_aggvar_2', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('aggvar_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('aggvar_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('num_rec', sa.BIGINT(), autoincrement=False, nullable=True),
                    redshift_distkey='grvar_1',
                    redshift_diststyle='KEY',
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.create_table('mv_tbl__offer_statistic_mv__0',
                    sa.Column('offer_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('epc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('cvr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('total_payout', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('total_click_last_30_days', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_payout_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('total_conversion_last_30_days', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('epc_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('cvr_last_30_days', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('accepted_application', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('total_application', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('acceptance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    redshift_distkey=None,
                    redshift_diststyle=None,
                    redshift_interleaved_sortkey=None,
                    redshift_sortkey=()
                    )
    op.drop_table('traffic_source', schema='mysql')
    op.drop_table('campaign', schema='mysql')
    op.drop_table('base_mysql_model', schema='mysql')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mv_tbl__offer_statistic_mv__0')
    op.drop_table('mv_tbl__budget_check_extracted_lifetime_mv__0')
    op.drop_table('mv_tbl__budget_check_extracted_daily_mv__0')
    op.drop_table('mv_tbl__budget_check_extracted_weekly_mv__0')
    op.drop_table('mv_tbl__advertiser_last30day_statistic_mv__0')
    op.drop_table('campaign_offer_request_log')
    op.drop_table('action_log')
    op.drop_table('lander_statistic')
    op.drop_table('traffic_source_statistic')
    op.drop_table('conversion')
    op.drop_table('offer_statistic')
    op.drop_table('mv_tbl__budget_check_extracted_monthly_mv__0')
    op.drop_table('offer_request_log')
    op.drop_table('mv_tbl__vertical_statistic_mv__0')
    op.drop_table('mv_tbl__country_statistic_mv__0')
    op.drop_table('mv_tbl__budget_check_extracted_yearly_mv__0')
    op.drop_table('postback_log')
    op.drop_table('mv_tbl__device_statistic_mv__0')
    op.drop_table('click_log')
    op.drop_table('landing_page_view_logs')
    op.drop_table('advertiser_statistic')
    op.drop_table('mv_tbl__conversion_board_mv__0')
    op.drop_table('campaign_request_log_bk')
    op.drop_table('campaign_statistic')
    with op.batch_alter_table('campaign_impression', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.text('"identity"(190997, 0, \'0,1\'::text)'))
        batch_op.alter_column('advertiser_id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              existing_nullable=True)
        batch_op.alter_column('campaign_uuid',
                              existing_type=sa.VARCHAR(length=256),
                              type_=sa.String(length=5000),
                              existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_campaign_impression_advertiser_id'), ['advertiser_id'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('proxy_name')
        batch_op.drop_column('device_type')
        batch_op.drop_column('isp')
        batch_op.drop_column('cost')
        batch_op.drop_column('lander_id')
        batch_op.drop_column('region')
        batch_op.drop_column('city')
        batch_op.drop_column('browser')
        batch_op.drop_column('language')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('traffic_source_id')
        batch_op.drop_column('mobile_carrier')
        batch_op.drop_column('timezone')
        batch_op.drop_column('cost_model')
        batch_op.drop_column('device_os_version')
        batch_op.drop_column('referer')
        batch_op.drop_column('ip')
        batch_op.drop_column('datetime')
        batch_op.drop_column('country')
        batch_op.drop_column('requesting_url')
        batch_op.drop_column('device_brand')
        batch_op.drop_column('browser_version')
        batch_op.drop_column('offer_id')
        batch_op.drop_column('impression_uuid')
        batch_op.drop_column('user_agent_string')
        batch_op.drop_column('device_model')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('device_os')
        batch_op.drop_column('postal')
        batch_op.drop_column('connection_type')

    with op.batch_alter_table('campaign_request_log', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.text('"identity"(653664, 0, \'0,1\'::text)'))
        batch_op.alter_column('campaign_uuid',
                              existing_type=sa.VARCHAR(length=256),
                              type_=sa.String(length=255),
                              existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_campaign_request_log_campaign_uuid'), ['campaign_uuid'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('var4')
        batch_op.drop_column('proxy_name')
        batch_op.drop_column('uuid')
        batch_op.drop_column('var1')
        batch_op.drop_column('device_type')
        batch_op.drop_column('isp')
        batch_op.drop_column('cost')
        batch_op.drop_column('lander_id')
        batch_op.drop_column('region')
        batch_op.drop_column('browser')
        batch_op.drop_column('city')
        batch_op.drop_column('language')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('var8')
        batch_op.drop_column('var7')
        batch_op.drop_column('traffic_source_id')
        batch_op.drop_column('mobile_carrier')
        batch_op.drop_column('timezone')
        batch_op.drop_column('device_os_version')
        batch_op.drop_column('var3')
        batch_op.drop_column('cost_model')
        batch_op.drop_column('referer')
        batch_op.drop_column('ip')
        batch_op.drop_column('var2')
        batch_op.drop_column('datetime')
        batch_op.drop_column('country')
        batch_op.drop_column('destination_url')
        batch_op.drop_column('var9')
        batch_op.drop_column('device_brand')
        batch_op.drop_column('requesting_url')
        batch_op.drop_column('var6')
        batch_op.drop_column('browser_version')
        batch_op.drop_column('campaign_impression_id')
        batch_op.drop_column('unique_id')
        batch_op.drop_column('user_agent_string')
        batch_op.drop_column('device_model')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('var10')
        batch_op.drop_column('device_os')
        batch_op.drop_column('postal')
        batch_op.drop_column('campaign_url')
        batch_op.drop_column('var5')
        batch_op.drop_column('click_uuid')
        batch_op.drop_column('lander_url')
        batch_op.drop_column('connection_type')
    # ### end Alembic commands ###
